
phases:
  install:
    commands:
      - curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 7.0
  pre_build:
    commands:
      - dotnet restore
  build:
    commands:
      - dotnet build
  post_build:
    commands:
      - dotnet publish -c Release -o publish --os linux
artifacts:
  files:
    - '**/*'
