services:

    api:
        container_name: todo-ai-service
        image: apicontainer:latest
        environment:
            - ASPNETCORE_ENVIRONMENT=docker
            - ASPNETCORE_URLS=http://+:80
        ports:
          - 80:80
        depends_on:
            db:
                condition: service_healthy

    db:
        container_name: mysqlcontainer
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: 'todo-ai-db'
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
        secrets:
            - db_root_password
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - my-db:/var/lib/mysql
        healthcheck:
          test: "mysql --version"
          interval: 10s
          timeout: 5s
          retries: 5

secrets:
    db_root_password:
        file: './db_root_password.txt'

volumes:
  my-db: