services:

    db:
        container_name: mysqlcontainer
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: 'todo-ai-db'
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
        secrets:
            - db_root_password
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - my-db:/var/lib/mysql

secrets:
    db_root_password:
        file: './db_root_password.txt'

volumes:
  my-db: